const KEY='ww_rockstar',PREF='ww_rockstar_pref';
const S=['Raccoon','Grey Squirrel','Red Squirrel','Flying Squirrel','Bat','Skunk','Groundhog','Bird','Snake','Opossum','Rodent','Carpenter Bee','Other'],ST=['Active','Scheduled','Waiting On Customer','Trapping','Exclusion','Repair','Warranty','Closed'],VT=['Inspection','Trap Set','Trap Check','Exclusion','Repair','Warranty Follow-Up','Other'],RS=['Open','Sealed','Needs Repair','Warranty Covered'],SV=['Low','Medium','High','Critical'],PT=['Before','Entry Point','Damage','Trap Placement','Droppings / Evidence','Repair During','After','Warranty'];
let db=JSON.parse(localStorage.getItem(KEY)||'{"jobs":[],"visits":[],"repairs":[],"photos":[],"signatures":[],"queue":[]}'),pref=JSON.parse(localStorage.getItem(PREF)||'{}'),sel=pref.sel||'',pendingGPS=null;
const pages=[['dash','🏠 Dashboard'],['jobs','🦝 Jobs'],['detail','📂 Job Detail'],['gps','📍 GPS Map'],['estimate','💵 Estimator'],['ai','🧠 AI Assistant'],['visits','📝 Visits'],['repairs','🔨 Repairs'],['photos','📸 Photos'],['contracts','✍️ Contracts'],['heat','🗺️ Heat Map'],['sync','☁️ Cloud Sync'],['data','💾 Data']];
function O(a,v=''){return a.map(x=>`<option ${x==v?'selected':''}>${x}</option>`).join('')}function E(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function now(){return new Date().toLocaleString()}function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}function J(i){return db.jobs.find(x=>x.id==i)}function tel(p){return'tel:'+String(p||'').replace(/[^\d+]/g,'')}
function snap(){localStorage.setItem(KEY+'_bak',JSON.stringify({saved:new Date().toISOString(),db}))}function savePref(){pref.sel=sel;localStorage.setItem(PREF,JSON.stringify(pref))}
function save(action='save'){if(action)db.queue.push({id:id(),action,at:new Date().toISOString()});localStorage.setItem(KEY,JSON.stringify(db));localStorage.setItem(KEY+'_last',new Date().toISOString());snap();render()}setInterval(snap,30000);addEventListener('beforeunload',snap);
function menu(){drawer.classList.toggle('open')}function closeM(i){document.getElementById(i).classList.remove('open')}function go(p){document.querySelectorAll('.view').forEach(x=>x.classList.remove('on'));document.getElementById(p).classList.add('on');label.textContent=pages.find(x=>x[0]==p)[1];drawer.classList.remove('open');render()}
function init(){nav.innerHTML=pages.map(p=>`<button onclick="go('${p[0]}')">${p[1]}</button>`).join('');[species,estSpecies,aiSpecies].forEach(x=>x.innerHTML=O(S));visitType.innerHTML=O(VT);rstatus.innerHTML=O(RS);rsev.innerHTML=O(SV);estSeverity.innerHTML=O(SV);photoTag.innerHTML=O(PT);syncUrl.value=localStorage.getItem(KEY+'_syncUrl')||'';if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
function addJob(){let j={id:id(),created:now(),updated:now(),status:'Active',customer:customer.value.trim(),phone:phone.value.trim(),address:address.value.trim(),town:town.value.trim()||'Unsorted',species:species.value,title:title.value.trim()||species.value+' job',scope:scope.value.trim(),warranty:'Not set',priority:'Normal',lat:pendingGPS?.lat||'',lng:pendingGPS?.lng||'',accuracy:pendingGPS?.accuracy||''};if(!j.customer||!j.address)return alert('Customer and address required.');db.jobs.unshift(j);sel=j.id;savePref();customer.value=phone.value=address.value=town.value=title.value=scope.value='';pendingGPS=null;save('job:create')}
function gpsFill(){gpsCurrent(pos=>{pendingGPS=pos;alert('GPS captured for next job: '+pos.lat+', '+pos.lng)})}
function gpsCurrent(cb){if(!navigator.geolocation){gpsOut.textContent='GPS not supported.';return}navigator.geolocation.getCurrentPosition(p=>{let g={lat:+p.coords.latitude.toFixed(6),lng:+p.coords.longitude.toFixed(6),accuracy:Math.round(p.coords.accuracy)};gpsOut.textContent='GPS: '+g.lat+', '+g.lng+' accuracy '+g.accuracy+'m';if(cb)cb(g);renderMap()},e=>gpsOut.textContent='GPS error: '+e.message,{enableHighAccuracy:true,timeout:12000})}
function addVisit(){if(!visitJob.value)return alert('Create a job first.');db.visits.unshift({id:id(),jobId:visitJob.value,type:visitType.value,note:visitNote.value.trim(),animals:+(animals.value||0),date:now()});sel=visitJob.value;savePref();visitNote.value=animals.value='';save('visit:create')}
function addRepair(){if(!repairJob.value)return alert('Create a job first.');db.repairs.unshift({id:id(),jobId:repairJob.value,location:rloc.value.trim(),status:rstatus.value,severity:rsev.value,materials:rmat.value.trim(),note:rnote.value.trim(),date:now()});sel=repairJob.value;savePref();rloc.value=rmat.value=rnote.value='';save('repair:create')}
function addPhoto(){if(!photoJob.value)return alert('Create a job first.');let f=photoFile.files[0];if(!f)return alert('Choose photo.');let r=new FileReader();r.onload=()=>{db.photos.unshift({id:id(),jobId:photoJob.value,tag:photoTag.value,data:r.result,date:now()});sel=photoJob.value;savePref();photoFile.value='';save('photo:create')};r.readAsDataURL(f)}
function estimateJob(j){let base={Bat:950,Raccoon:650,'Grey Squirrel':550,'Red Squirrel':575,'Flying Squirrel':750,Skunk:450,Groundhog:450,'Carpenter Bee':350}[j.species]||500;return Math.round(base*1.35)}
function score(j){let v=db.visits.some(x=>x.jobId==j.id),p=db.photos.some(x=>x.jobId==j.id),rr=db.repairs.filter(x=>x.jobId==j.id),sig=db.signatures.some(x=>x.jobId==j.id);return Math.min(100,(v?25:0)+(p?25:0)+(rr.length?25:0)+(sig?25:0))}
function card(j){let v=db.visits.filter(x=>x.jobId==j.id).length,r=db.repairs.filter(x=>x.jobId==j.id).length,p=db.photos.filter(x=>x.jobId==j.id).length,s=score(j);return`<div class="card stack"><div class="row"><div class="title">${E(j.title)}</div><span class="pill">${E(j.status)}</span></div><div class="tiny">${E(j.customer)} · ${E(j.phone)}</div><div>${E(j.address)}</div><div><span class="pill">${E(j.town)}</span><span class="pill">${E(j.species)}</span><span class="pill">${v} visits</span><span class="pill">${r} repairs</span><span class="pill">${p} photos</span>${j.lat?'<span class="pill">GPS</span>':''}</div><div class="prog"><div class="bar" style="width:${s}%"></div></div><div class="tiny">Score ${s}% · Est $${estimateJob(j)}</div><div class="row"><button class="blue" onclick="sel='${j.id}';savePref();go('detail')">Open</button><a class="btn" href="${tel(j.phone)}">Call</a></div></div>`}
function estimate(){let base={Bat:950,Raccoon:650,'Grey Squirrel':550,'Red Squirrel':575,'Flying Squirrel':750,Skunk:450,Groundhog:450,'Carpenter Bee':350}[estSpecies.value]||500,m={Low:1,Medium:1.35,High:1.8,Critical:2.4}[estSeverity.value],price=Math.round(base*m+(+estHeight.value||0)*12+(+estFeet.value||0)*18+(+estTrips.value||3)*85);estimateOut.value=`Recommended estimate: $${price}\nSpecies: ${estSpecies.value}\nSeverity: ${estSeverity.value}\nIncludes inspection/travel, exclusion complexity, repair size, and profit buffer.`}
function hint(s){return({Raccoon:'attic/chimney/latrine patterns; inspect roof access and soffits.','Grey Squirrel':'larger attic nesting, fascia/gable vent risk.','Red Squirrel':'aggressive chewing, cone caches, repeat entry attempts.','Flying Squirrel':'night activity, colonies, wall/attic movement.',Bat:'roost timing, guano, staining, legal exclusion window.',Skunk:'den and odor zones around decks/sheds.',Groundhog:'burrow/foundation/deck undermining risk.','Carpenter Bee':'fascia/deck recurrence and residual treatment zones.'}[s]||'track behavior, seasonality, recurrence')}
function aiSuggest(){let o=aiObs.value.toLowerCase(),tips=[`Species: ${aiSpecies.value}`,`Season: ${aiSeason.value}`,hint(aiSpecies.value)];if(o.includes('night'))tips.push('Night activity points toward flying squirrel, bat, raccoon, or mice depending on sound.');if(o.includes('soffit')||o.includes('fascia'))tips.push('Inspect soffit returns, fascia corners, roof-to-wall joints.');if(o.includes('attic'))tips.push('Check insulation trails, nesting zones, rub marks, urine staining, secondary exits.');aiOut.value='- '+tips.join('\\n- ')}
function dictate(el){let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return alert('Speech recognition not supported. Try Chrome.');let r=new R();r.lang='en-US';r.onresult=e=>{el.value+=(el.value?' ':'')+e.results[0][0].transcript};r.start()}
function openSig(){sigJob.innerHTML=db.jobs.map(j=>`<option value="${j.id}">${E(j.title)} — ${E(j.customer)}</option>`).join('');sigM.classList.add('open');setupSig()}
let drawing=false;function setupSig(){let c=sigCanvas,ctx=c.getContext('2d');c.width=c.clientWidth;c.height=c.clientHeight;ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#000';c.onpointerdown=e=>{drawing=true;ctx.beginPath();ctx.moveTo(e.offsetX,e.offsetY)};c.onpointermove=e=>{if(drawing){ctx.lineTo(e.offsetX,e.offsetY);ctx.stroke()}};c.onpointerup=()=>drawing=false}
function clearSig(){let c=sigCanvas;c.getContext('2d').clearRect(0,0,c.width,c.height)}function saveSig(){db.signatures.unshift({id:id(),jobId:sigJob.value,name:sigName.value,date:now(),data:sigCanvas.toDataURL()});closeM('sigM');save('signature:create')}
function contractText(){let j=J(contractJob.value);if(!j)return;contractOut.value=`Wildlife Whisperer LLC Service Agreement\\nCustomer: ${j.customer}\\nAddress: ${j.address}\\nJob: ${j.title}\\nSpecies: ${j.species}\\nScope: ${j.scope}\\nWarranty: ${j.warranty}\\nEstimated Price: $${estimateJob(j)}\\n\\nCustomer authorizes inspection, removal, exclusion, repair, sanitation, prevention, and related nuisance wildlife services. Warranty applies only to listed sealed/repaired areas.`}
function renderMap(){let jobs=db.jobs.filter(j=>j.lat&&j.lng),box=mapbox;if(!box)return;if(!jobs.length){box.innerHTML='<div class="card tiny">No GPS jobs yet.</div>';return}let minLat=Math.min(...jobs.map(j=>+j.lat)),maxLat=Math.max(...jobs.map(j=>+j.lat)),minLng=Math.min(...jobs.map(j=>+j.lng)),maxLng=Math.max(...jobs.map(j=>+j.lng));box.innerHTML=jobs.map(j=>{let x=maxLng==minLng?50:((j.lng-minLng)/(maxLng-minLng))*86+7,y=maxLat==minLat?50:(100-((j.lat-minLat)/(maxLat-minLat))*86-7);return`<div class="pin" style="left:${x}%;top:${y}%"><span>${E(j.species)} · ${E(j.town)}</span></div>`}).join('')}
function renderDetail(){let j=J(sel);if(!j){detailBox.innerHTML='<div class="card tiny">No job selected.</div>';return}let vs=db.visits.filter(v=>v.jobId==j.id),rs=db.repairs.filter(r=>r.jobId==j.id),ps=db.photos.filter(p=>p.jobId==j.id);detailBox.innerHTML=`<div class="card stack"><h2 style="margin:0">${E(j.title)}</h2><div>${E(j.customer)} · <a style="color:var(--blue)" href="${tel(j.phone)}">${E(j.phone)}</a></div><div class="tiny">${E(j.address)} · ${E(j.town)} · ${E(j.species)} ${j.lat?'· GPS '+j.lat+', '+j.lng:''}</div><div class="prog"><div class="bar" style="width:${score(j)}%"></div></div><div>${E(j.scope)}</div><div class="tiny">Warranty: ${E(j.warranty)} · Est $${estimateJob(j)}</div></div><div class="section">Property History</div><div class="card tiny">${historyFor(j)}</div><div class="section">Visits</div>${vs.map(v=>`<div class="card"><b>${E(v.type)}</b><div class="tiny">${E(v.date)} · Animals ${v.animals||0}</div><div>${E(v.note)}</div></div>`).join('')||'<div class="card tiny">No visits.</div>'}<div class="section">Repairs</div>${rs.map(r=>`<div class="card"><b>${E(r.location)}</b><span class="pill">${E(r.status)}</span><span class="pill">${E(r.severity)}</span><div>${E(r.note)}</div></div>`).join('')||'<div class="card tiny">No repairs.</div>'}<div class="section">Photos</div>${ps.map(p=>`<div class="card row"><img class="photo" src="${p.data}"><div><b>${E(p.tag)}</b><div class="tiny">${E(p.date)}</div></div></div>`).join('')||'<div class="card tiny">No photos.</div>'}`}
function historyFor(j){let r=db.jobs.filter(x=>x.address.toLowerCase()==j.address.toLowerCase()||x.phone==j.phone);return r.map(x=>`${x.created}: ${x.species} — ${x.title} — ${x.status}`).join('\\n')||'No property history yet.'}
function renderLists(){visitList.innerHTML=db.visits.map(v=>`<div class="card"><b>${E(v.type)}</b><div class="tiny">${E(J(v.jobId)?.title||'Unknown')} · ${E(v.date)}</div><div>${E(v.note)}</div></div>`).join('')||'<div class="card tiny">No visits.</div>';repairList.innerHTML=db.repairs.map(r=>`<div class="card"><b>${E(r.location)}</b><div class="tiny">${E(J(r.jobId)?.title||'Unknown')}</div><span class="pill">${E(r.status)}</span><span class="pill">${E(r.severity)}</span><div>${E(r.note)}</div></div>`).join('')||'<div class="card tiny">No repairs.</div>';photoList.innerHTML=db.photos.map(p=>`<div class="card row"><img class="photo" src="${p.data}"><div><b>${E(p.tag)}</b><div class="tiny">${E(J(p.jobId)?.title||'Unknown')} · ${E(p.date)}</div></div></div>`).join('')||'<div class="card tiny">No photos.</div>'}
function renderHeat(){let tc={};db.jobs.forEach(j=>tc[j.town||'Unsorted']=(tc[j.town||'Unsorted']||0)+1);heatGrid.innerHTML=Object.entries(tc).sort((a,b)=>b[1]-a[1]).map(([t,c])=>`<div class="hcell h${Math.min(5,c)}"><div class="row"><b>${E(t)}</b><span class="badge ${c>3?'bad':c>1?'warn':''}">${c} jobs</span></div>${speciesForTown(t)}</div>`).join('')||'<div class="card tiny">No location data.</div>';let sc={};db.jobs.forEach(j=>sc[j.species]=(sc[j.species]||0)+1);intel.innerHTML=Object.entries(sc).sort((a,b)=>b[1]-a[1]).map(([s,c])=>`<div class="card"><b>${E(s)}</b><div class="tiny">${c} jobs · ${hint(s)}</div></div>`).join('')||'<div class="card tiny">No species data.</div>'}
function speciesForTown(t){let c={};db.jobs.filter(j=>(j.town||'Unsorted')==t).forEach(j=>c[j.species]=(c[j.species]||0)+1);return Object.entries(c).map(([s,n])=>`<span class="pill">${E(s)} ${n}</span>`).join('')}
function saveSyncUrl(){localStorage.setItem(KEY+'_syncUrl',syncUrl.value.trim());alert('Endpoint saved.')}async function syncNow(){let url=localStorage.getItem(KEY+'_syncUrl')||syncUrl.value.trim();if(!url)return alert('Add endpoint first.');try{let res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({device:'android-fieldops',db,queue:db.queue})});syncLog.value='Sync response: '+res.status+' '+await res.text();if(res.ok){db.queue=[];save('')}}catch(e){syncLog.value='Sync failed: '+e.message}}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='wildlife-fieldops-rockstar-backup.json';a.click()}function importData(){try{let n=JSON.parse(importBox.value);if(n.jobs&&n.visits&&n.repairs&&n.photos){db=n;save('import');alert('Imported.')}else alert('Bad format.')}catch(e){alert('Bad JSON.')}}
function recover(){let b=JSON.parse(localStorage.getItem(KEY+'_bak')||'{}');if(b.db&&confirm('Recover snapshot '+b.saved+'?')){db=b.db;save('recover')}}function wipe(){if(confirm('Wipe all local data?')){db={jobs:[],visits:[],repairs:[],photos:[],signatures:[],queue:[]};save('wipe')}}
function render(){if(!sel&&db.jobs[0])sel=db.jobs[0].id;let jo=db.jobs.map(j=>`<option value="${j.id}" ${j.id==sel?'selected':''}>${E(j.title)} — ${E(j.customer)}</option>`).join('');[visitJob,repairJob,photoJob,detailSel,contractJob].forEach(x=>x.innerHTML=jo);m1.textContent=db.jobs.filter(j=>j.status!='Closed').length;m2.textContent='$'+db.jobs.filter(j=>j.status!='Closed').reduce((a,j)=>a+estimateJob(j),0);m3.textContent=db.queue.length;m4.textContent=db.photos.length;let q=(search?.value||'').toLowerCase(),list=db.jobs.filter(j=>(j.title+j.customer+j.address+j.town+j.species+j.scope+j.status).toLowerCase().includes(q));jobList.innerHTML=list.map(card).join('')||'<div class="card tiny">No jobs.</div>';recent.innerHTML=db.jobs.slice(0,5).map(card).join('')||'<div class="card tiny">No jobs yet.</div>';renderDetail();renderLists();renderHeat();renderMap();sigList.innerHTML=db.signatures.map(s=>`<div class="card row"><img class="photo" src="${s.data}"><div><b>${E(s.name)}</b><div class="tiny">${E(J(s.jobId)?.title||'Unknown')} · ${E(s.date)}</div></div></div>`).join('')||'<div class="card tiny">No signatures.</div>';persist.textContent='Persistent memory active. Last saved: '+(localStorage.getItem(KEY+'_last')?new Date(localStorage.getItem(KEY+'_last')).toLocaleString():'not saved yet')+'. Auto snapshot every 30 seconds.'}
init();render();