# Gradle settings
org.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.caching=true
org.gradle.parallel=true

# Android settings
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35

# Kotlin settings
kotlin.code.style=official
