package com.strobingn.wildlifefieldops.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import com.strobingn.wildlifefieldops.ui.components.SignaturePadWithControls
import com.strobingn.wildlifefieldops.ui.theme.*
import com.strobingn.wildlifefieldops.ui.viewmodel.ContractViewModel
import java.text.SimpleDateFormat
import java.util.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ContractScreen(
    jobId: String? = null,
    onBack: () -> Unit,
    viewModel: ContractViewModel = hiltViewModel()
) {
    val scrollState = rememberScrollState()
    var customerName by remember { mutableStateOf("") }
    var customerAddress by remember { mutableStateOf("") }
    var serviceDescription by remember { mutableStateOf("") }
    var estimatedValue by remember { mutableStateOf("") }
    var warrantyMonths by remember { mutableStateOf("12") }
    var showSignaturePad by remember { mutableStateOf(false) }
    var signatureCaptured by remember { mutableStateOf(false) }
    var showPdfDialog by remember { mutableStateOf(false) }

    val dateFormat = SimpleDateFormat("MMMM dd, yyyy", Locale.US)
    val today = dateFormat.format(Date())

    LaunchedEffect(jobId) {
        jobId?.let { viewModel.loadJob(it) }
    }

    val job by viewModel.job.collectAsState()
    val pdfGenerated by viewModel.pdfGenerated.collectAsState()
    val pdfPath by viewModel.pdfPath.collectAsState()
    val isGeneratingPdf by viewModel.isGeneratingPdf.collectAsState()
    val context = androidx.compose.ui.platform.LocalContext.current
    var showPdfResult by remember { mutableStateOf(false) }

    LaunchedEffect(pdfGenerated) {
        if (pdfGenerated) showPdfResult = true
    }

    LaunchedEffect(job) {
        job?.let {
            customerName = it.customerName
            customerAddress = it.address
            serviceDescription = it.description
            estimatedValue = it.estimatedValue.toString()
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Digital Contract", color = TextPrimary) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back", tint = TextPrimary)
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = BackgroundDark)
            )
        },
        containerColor = BackgroundDark
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(scrollState)
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Contract header
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = BackgroundCard),
                shape = RoundedCornerShape(12.dp)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text(
                        "WILDLIFE REMOVAL SERVICE AGREEMENT",
                        style = MaterialTheme.typography.titleMedium,
                        color = TextPrimary,
                        fontWeight = FontWeight.Bold
                    )
                    Spacer(modifier = Modifier.height(4.dp))
                    Text("Date: $today", color = TextSecondary, style = MaterialTheme.typography.bodySmall)
                }
            }

            // Customer info
            ContractSection("Customer Information") {
                OutlinedTextField(
                    value = customerName,
                    onValueChange = { customerName = it },
                    label = { Text("Customer Name") },
                    modifier = Modifier.fillMaxWidth(),
                    colors = OutlinedTextFieldDefaults.colors(
                        focusedTextColor = TextPrimary,
                        unfocusedTextColor = TextPrimary,
                        focusedLabelColor = PrimaryGreen,
                        unfocusedLabelColor = TextSecondary
                    )
                )
                Spacer(modifier = Modifier.height(8.dp))
                OutlinedTextField(
                    value = customerAddress,
                    onValueChange = { customerAddress = it },
                    label = { Text("Service Address") },
                    modifier = Modifier.fillMaxWidth(),
                    minLines = 2,
                    colors = OutlinedTextFieldDefaults.colors(
                        focusedTextColor = TextPrimary,
                        unfocusedTextColor = TextPrimary,
                        focusedLabelColor = PrimaryGreen,
                        unfocusedLabelColor = TextSecondary
                    )
                )
            }

            // Service details
            ContractSection("Service Details") {
                OutlinedTextField(
                    value = serviceDescription,
                    onValueChange = { serviceDescription = it },
                    label = { Text("Description of Services") },
                    modifier = Modifier.fillMaxWidth(),
                    minLines = 3,
                    colors = OutlinedTextFieldDefaults.colors(
                        focusedTextColor = TextPrimary,
                        unfocusedTextColor = TextPrimary,
                        focusedLabelColor = PrimaryGreen,
                        unfocusedLabelColor = TextSecondary
                    )
                )
                Spacer(modifier = Modifier.height(8.dp))
                Row(modifier = Modifier.fillMaxWidth()) {
                    OutlinedTextField(
                        value = estimatedValue,
                        onValueChange = { estimatedValue = it },
                        label = { Text("Estimated Cost ($)") },
                        modifier = Modifier.weight(1f),
                        colors = OutlinedTextFieldDefaults.colors(
                            focusedTextColor = TextPrimary,
                            unfocusedTextColor = TextPrimary,
                            focusedLabelColor = PrimaryGreen,
                            unfocusedLabelColor = TextSecondary
                        )
                    )
                    Spacer(modifier = Modifier.width(8.dp))
                    OutlinedTextField(
                        value = warrantyMonths,
                        onValueChange = { warrantyMonths = it },
                        label = { Text("Warranty (mo)") },
                        modifier = Modifier.weight(1f),
                        colors = OutlinedTextFieldDefaults.colors(
                            focusedTextColor = TextPrimary,
                            unfocusedTextColor = TextPrimary,
                            focusedLabelColor = PrimaryGreen,
                            unfocusedLabelColor = TextSecondary
                        )
                    )
                }
            }

            // Terms
            ContractSection("Terms & Conditions") {
                val terms = buildString {
                    append("1. Wildlife Whisperer LLC agrees to perform the described wildlife removal services.\n\n")
                    append("2. Customer grants access to property for inspection, service, and follow-up visits.\n\n")
                    append("3. Payment is due upon completion of services unless otherwise agreed in writing.\n\n")
                    append("4. Warranty covers workmanship and materials for the specified period.\n\n")
                    append("5. Wildlife Whisperer LLC is not liable for pre-existing structural damage.\n\n")
                    append("6. This agreement constitutes the entire understanding between parties.")
                }
                Text(terms, color = TextSecondary, style = MaterialTheme.typography.bodySmall)
            }

            // Signature section
            ContractSection("Electronic Signature") {
                if (!signatureCaptured) {
                    if (!showSignaturePad) {
                        Button(
                            onClick = { showSignaturePad = true },
                            modifier = Modifier.fillMaxWidth(),
                            colors = ButtonDefaults.buttonColors(containerColor = PrimaryGreen)
                        ) {
                            Icon(Icons.Default.Draw, contentDescription = null)
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("Sign Contract")
                        }
                    } else {
                        SignaturePadWithControls(
                            onSignatureCaptured = { points ->
                                viewModel.saveSignature(points)
                                signatureCaptured = true
                                showSignaturePad = false
                            },
                            onClear = { signatureCaptured = false }
                        )
                    }
                } else {
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        colors = CardDefaults.cardColors(containerColor = PrimaryGreen.copy(alpha = 0.15f)),
                        shape = RoundedCornerShape(12.dp)
                    ) {
                        Row(
                            modifier = Modifier.padding(16.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Icon(Icons.Default.CheckCircle, contentDescription = null, tint = PrimaryGreen)
                            Spacer(modifier = Modifier.width(12.dp))
                            Column {
                                Text("Signature captured", color = TextPrimary, fontWeight = FontWeight.Bold)
                                Text("Signed by: $customerName", color = TextSecondary, style = MaterialTheme.typography.bodySmall)
                                Text("Date: $today", color = TextSecondary, style = MaterialTheme.typography.bodySmall)
                            }
                        }
                    }
                    Spacer(modifier = Modifier.height(8.dp))
                    TextButton(
                        onClick = {
                            signatureCaptured = false
                            showSignaturePad = false
                        },
                        modifier = Modifier.align(Alignment.CenterHorizontally)
                    ) {
                        Text("Re-sign", color = TextSecondary)
                    }
                }
            }

            // Action buttons
            Spacer(modifier = Modifier.height(16.dp))
            Button(
                onClick = { showPdfDialog = true },
                modifier = Modifier.fillMaxWidth(),
                enabled = signatureCaptured && customerName.isNotBlank() && !isGeneratingPdf,
                colors = ButtonDefaults.buttonColors(containerColor = PrimaryGreen)
            ) {
                if (isGeneratingPdf) {
                    CircularProgressIndicator(
                        modifier = Modifier.size(18.dp),
                        color = Color.White,
                        strokeWidth = 2.dp
                    )
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Generating…")
                } else {
                    Icon(Icons.Default.PictureAsPdf, contentDescription = null)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Generate PDF Contract")
                }
            }

            Spacer(modifier = Modifier.height(8.dp))
            OutlinedButton(
                onClick = {
                    viewModel.saveContract(
                        customerName = customerName,
                        address = customerAddress,
                        description = serviceDescription,
                        estimatedValue = estimatedValue.toDoubleOrNull() ?: 0.0,
                        warrantyMonths = warrantyMonths.toIntOrNull() ?: 12
                    )
                },
                modifier = Modifier.fillMaxWidth(),
                enabled = customerName.isNotBlank()
            ) {
                Icon(Icons.Default.Save, contentDescription = null)
                Spacer(modifier = Modifier.width(8.dp))
                Text("Save Contract")
            }
        }
    }

    if (showPdfDialog) {
        AlertDialog(
            onDismissRequest = { showPdfDialog = false },
            title = { Text("Generate PDF", color = TextPrimary) },
            text = { Text("This will generate a signed PDF contract and save it locally, ready to share.", color = TextSecondary) },
            confirmButton = {
                TextButton(
                    onClick = {
                        viewModel.generatePdfContract(
                            customerName = customerName,
                            address = customerAddress,
                            description = serviceDescription,
                            estimatedValue = estimatedValue.toDoubleOrNull() ?: 0.0,
                            warrantyMonths = warrantyMonths.toIntOrNull() ?: 12,
                            signatureDate = today
                        )
                        showPdfDialog = false
                    }
                ) {
                    Text("Generate", color = PrimaryGreen)
                }
            },
            dismissButton = {
                TextButton(onClick = { showPdfDialog = false }) {
                    Text("Cancel", color = TextSecondary)
                }
            },
            containerColor = BackgroundCard
        )
    }

    // PDF result dialog with share/view actions
    if (showPdfResult && !pdfPath.isNullOrBlank()) {
        AlertDialog(
            onDismissRequest = {
                showPdfResult = false
                viewModel.clearPdfStatus()
            },
            title = { Text("Contract PDF Ready", color = TextPrimary) },
            text = {
                Text(
                    "Saved to:\n$pdfPath",
                    color = TextSecondary,
                    style = MaterialTheme.typography.bodySmall
                )
            },
            confirmButton = {
                TextButton(
                    onClick = {
                        pdfPath?.let { shareContractPdf(context, it) }
                        showPdfResult = false
                        viewModel.clearPdfStatus()
                    }
                ) {
                    Icon(Icons.Default.Share, contentDescription = null, tint = PrimaryGreen)
                    Spacer(modifier = Modifier.width(4.dp))
                    Text("Share", color = PrimaryGreen)
                }
            },
            dismissButton = {
                TextButton(
                    onClick = {
                        showPdfResult = false
                        viewModel.clearPdfStatus()
                    }
                ) {
                    Text("Done", color = TextSecondary)
                }
            },
            containerColor = BackgroundCard
        )
    }
}

/** Share the generated contract PDF through the system share sheet via FileProvider. */
private fun shareContractPdf(context: android.content.Context, path: String) {
    runCatching {
        val file = java.io.File(path)
        val uri = androidx.core.content.FileProvider.getUriForFile(
            context,
            "${context.packageName}.provider",
            file
        )
        val intent = android.content.Intent(android.content.Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(android.content.Intent.EXTRA_STREAM, uri)
            addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(android.content.Intent.createChooser(intent, "Share Contract"))
    }.onFailure {
        android.util.Log.e("ContractScreen", "Share failed", it)
    }
}

@Composable
private fun ContractSection(title: String, content: @Composable ColumnScope.() -> Unit) {
    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
        Text(title, color = TextPrimary, fontWeight = FontWeight.Bold, style = MaterialTheme.typography.titleSmall)
        Card(
            modifier = Modifier.fillMaxWidth(),
            colors = CardDefaults.cardColors(containerColor = BackgroundCard),
            shape = RoundedCornerShape(12.dp)
        ) {
            Column(modifier = Modifier.padding(16.dp), content = content)
        }
    }
}
