package com.strobingn.wildlifefieldops.ui.screens

import android.graphics.pdf.PdfDocument
import android.os.Environment
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import java.io.File
import java.io.FileOutputStream

@Composable
fun InvoiceScreen(
    job: Job? = null, // from nav or state
    onBack: () -> Unit = {}
) {
    var invoiceGenerated by remember { mutableStateOf(false) }
    var pdfPath by remember { mutableStateOf("") }

    Column(modifier = Modifier.fillMaxSize().padding(16.dp)) {
        TopAppBar(title = { Text("Invoicing & PDF Reports") }, navigationIcon = {
            IconButton(onClick = onBack) { Icon(Icons.Default.ArrowBack, contentDescription = "Back") }
        })

        Text("Generate Invoice for Job: ${job?.title ?: "Sample Job"}")
        Spacer(Modifier.height(16.dp))

        Button(onClick = {
            val path = generateInvoicePDF(job)
            pdfPath = path
            invoiceGenerated = true
        }) {
            Text("Generate Invoice PDF")
        }

        if (invoiceGenerated) {
            Text("PDF generated: $pdfPath")
            Button(onClick = { /* Open or share PDF */ }) {
                Text("View/Share Report")
            }
        }

        Spacer(Modifier.height(16.dp))
        Text("PDF Reports: Job summaries, revenue, wildlife stats, contracts")
    }
}

fun generateInvoicePDF(job: Job?): String {
    val pdfDocument = PdfDocument()
    val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4
    val page = pdfDocument.startPage(pageInfo)
    val canvas = page.canvas

    // Simple PDF content
    val paint = android.graphics.Paint()
    paint.textSize = 20f
    canvas.drawText("Wildlife FieldOps Invoice", 50f, 50f, paint)
    canvas.drawText("Job: ${job?.title ?: "N/A"}", 50f, 100f, paint)
    canvas.drawText("Client: ${job?.client ?: "N/A"}", 50f, 130f, paint)
    canvas.drawText("Amount: $${job?.estimatedValue ?: 0}", 50f, 160f, paint)
    canvas.drawText("Date: ${java.text.SimpleDateFormat("yyyy-MM-dd").format(java.util.Date())}", 50f, 190f, paint)
    // Add more lines for items, totals, terms

    pdfDocument.finishPage(page)

    val file = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), "invoice_${System.currentTimeMillis()}.pdf")
    pdfDocument.writeTo(FileOutputStream(file))
    pdfDocument.close()

    return file.absolutePath
}